def int_combinations(lower_a, upper_a, lower_b, upper_b):
    """Finds number of distinct terms generated by a ** b from lower_a <= a <= upper_a
        and lower_b <= b <= upper_b"""
    x = lower_a
    lst = []
    while x <= upper_a:
        y = lower_b
        while y <= upper_b:
            if x ** y not in lst:
                lst.append(x ** y)
            y += 1
        x += 1
    print(len(lst))


int_combinations(2, 100, 2, 100) 
